export type MoodCategory =
  | "Positive"
  | "LowEnergy"
  | "HighEnergy"
  | "Love"
  | "Spiritual"
  | "Mental"
  | "Stress"
  | "Creative"
  | "Confidence"
  | "Social"
  | "Healing"
  | "Focus"
  | "Rest"
  | "Growth"
  | "Pain";

export interface MoodItem {
  label: string;
  emoji: string;
}

export interface MoodGroup {
  key: MoodCategory;
  title: string;
  moods: MoodItem[];
}

export const moodGroups: MoodGroup[] = [
  {
    key: "Positive",
    title: "Positive",
    moods: [
      { label: "Happy", emoji: "😄" },
      { label: "Grateful", emoji: "💛" },
      { label: "Hopeful", emoji: "🌈" },
      { label: "Content", emoji: "🙂" },
      { label: "Peaceful", emoji: "🕊️" },
      { label: "Joyful", emoji: "😁" },
      { label: "Optimistic", emoji: "🌞" },
      { label: "Satisfied", emoji: "😊" },
      { label: "Blessed", emoji: "🙏" },
      { label: "Light", emoji: "✨" },
      { label: "Energized", emoji: "⚡" },
    { label: "Uplifted", emoji: "🌤️" },
    { label: "Fulfilled", emoji: "🧘" },
    { label: "Proud", emoji: "🏆" },
    { label: "Loved", emoji: "❤️" },
    { label: "Appreciated", emoji: "🤍" },
    { label: "Calm-happy", emoji: "😊" },
    { label: "Free", emoji: "🕊️" },
    { label: "Safe", emoji: "🛡️" },
    { label: "Warm", emoji: "☀️" },
    { label: "Balanced", emoji: "⚖️" },
    { label: "Thankful", emoji: "🙌" },
    { label: "Radiant", emoji: "✨" },
    { label: "Grounded", emoji: "🌱" },
    { label: "Connected", emoji: "🔗" },
    { label: "Supported", emoji: "🤝" },
    { label: "Relieved", emoji: "😮‍💨" },
    { label: "Encouraged", emoji: "💬" },
    { label: "Hope-filled", emoji: "🌅" },
    { label: "Light-hearted", emoji: "💫" },
    { label: "Serene", emoji: "🌊" },
    { label: "Smiling", emoji: "🙂" },
    { label: "Gentle", emoji: "💛" },
    { label: "At peace", emoji: "🕯️" },
    { label: "Comforted", emoji: "🛋️" },
    { label: "Open-hearted", emoji: "💖" },
    { label: "Refreshed", emoji: "🚿" },
    { label: "Reassured", emoji: "🤲" },
    { label: "Content-inside", emoji: "🌼" },
    { label: "Whole", emoji: "🟡" },    
 // (zaka iya kara har su zama 30)
    ],
  },
  {
    key: "LowEnergy",
    title: "Low energy",
    moods: [
      { label: "Tired", emoji: "😴" },
      { label: "Exhausted", emoji: "🥱" },
      { label: "Sad", emoji: "😢" },
      { label: "Lonely", emoji: "🥺" },
      { label: "Empty", emoji: "🫥" },
      { label: "Drained", emoji: "🔋" },
      { label: "Weak", emoji: "😔" },
      { label: "Exhausted", emoji: "😩" },
    { label: "Burnt out", emoji: "🔥" },
    { label: "Heavy", emoji: "😔" },
    { label: "Slow", emoji: "🐌" },
    { label: "Foggy", emoji: "🌫️" },
    { label: "Weary", emoji: "🧎" },
    { label: "Worn out", emoji: "🪫" },
    { label: "Lethargic", emoji: "😶" },
    { label: "Unmotivated", emoji: "💤" },
    { label: "Flat", emoji: "😐" },
    { label: "Overwhelmed", emoji: "😵" },
    { label: "Numb", emoji: "😶‍🌫️" },
    { label: "Mentally tired", emoji: "🧠" },
    { label: "Emotionally drained", emoji: "💧" },
    { label: "Stuck", emoji: "🪨" },
    { label: "Quiet", emoji: "😶" },
    { label: "Low focus", emoji: "🔍" },
    { label: "Faded", emoji: "🎚️" },
    { label: "Empty inside", emoji: "🕳️" },
    { label: "Restless tired", emoji: "😮‍💨" },
    { label: "Slow-minded", emoji: "🧠🐌" },
    { label: "Waking tired", emoji: "🌅😴" },
    { label: "Physically weak", emoji: "🦵" },
    { label: "Emotionally heavy", emoji: "🫂" },
    { label: "Disconnected", emoji: "🔌" },
    { label: "Dull", emoji: "🪶" },
    { label: "Low spirit", emoji: "🌑" },
    { label: "Need rest", emoji: "🛏️" },
    { label: "Need silence", emoji: "🤫" },
    { label: "Shutdown mode", emoji: "⏸️" },
    ],
  },
  {
    key: "HighEnergy",
    title: "High energy",
    moods: [
      { label: "Excited", emoji: "🤩" },
      { label: "Motivated", emoji: "💪" },
      { label: "Energetic", emoji: "⚡" },
      { label: "Driven", emoji: "🏃‍♂️" },
      { label: "Playful", emoji: "😜" },
      { label: "Energized", emoji: "⚡" },
    { label: "Fired up", emoji: "🔥" },
    { label: "Hyper", emoji: "😆" },
    { label: "Pumped", emoji: "💥" },
    { label: "Alive", emoji: "🌟" },
    { label: "On fire", emoji: "🔥🔥" },
    { label: "Electric", emoji: "⚡⚡" },
    { label: "Rush", emoji: "🏃‍♂️" },
    { label: "Full of life", emoji: "🌈" },
    { label: "Uplifted", emoji: "🚀" },
    { label: "Invincible", emoji: "🛡️" },
    { label: "Charged", emoji: "🔋" },
    { label: "Peak mode", emoji: "🏔️" },
    { label: "Overjoyed", emoji: "😄" },
    { label: "Bold", emoji: "🦁" },
    { label: "Fearless", emoji: "🐯" },
    { label: "Powerful", emoji: "💪" },
    { label: "Limitless", emoji: "♾️" },
    { label: "Winning", emoji: "🏆" },
    { label: "Amped", emoji: "🔊" },
    { label: "Action mode", emoji: "▶️" },
    { label: "Fast lane", emoji: "🏎️" },
    { label: "Explosive", emoji: "💣" },
    { label: "Confident energy", emoji: "😎⚡" },
    { label: "High vibe", emoji: "✨" },
    { label: "Let’s go", emoji: "🚀🔥" },
    { label: "Flowing", emoji: "🌊⚡" },
    { label: "Activated", emoji: "🧠⚡" },
    { label: "Charged up", emoji: "🔌" },
    { label: "Prime energy", emoji: "👑" },   
],
  },
  {
    key: "Love",
    title: "Love",
    moods: [
      { label: "Romantic", emoji: "💖" },
      { label: "Affectionate", emoji: "🥰" },
      { label: "Loved", emoji: "❤️" },
      { label: "Loved", emoji: "💖" },
    { label: "Loving", emoji: "🫶" },
    { label: "In love", emoji: "💕" },
    { label: "Deeply connected", emoji: "🔗❤️" },
    { label: "Affectionate", emoji: "🤗" },
    { label: "Tender", emoji: "🌸" },
    { label: "Warm-hearted", emoji: "🔥💛" },
    { label: "Cherished", emoji: "💎" },
    { label: "Adored", emoji: "🥰" },
    { label: "Devoted", emoji: "💍" },
    { label: "Intimate", emoji: "🕯️" },
    { label: "Soft inside", emoji: "🧸" },
    { label: "Safe with you", emoji: "🏡❤️" },
    { label: "Romantic soul", emoji: "🌹" },
    { label: "Emotionally close", emoji: "🫂" },
    { label: "Heart full", emoji: "💓" },
    { label: "Gentle love", emoji: "🍃" },
    { label: "Caring deeply", emoji: "🤍" },
    { label: "Soul connection", emoji: "✨" },
    { label: "Falling for you", emoji: "💘" },
    { label: "Pure love", emoji: "🤍🌼" },
    { label: "Loyal", emoji: "❤️‍🔥" },
    { label: "Sweet affection", emoji: "🍯" },
    { label: "Calm love", emoji: "🌙❤️" },
    { label: "Protective", emoji: "🛡️❤️" },
    { label: "Vulnerable", emoji: "💞" },
    { label: "Chosen", emoji: "💌" },
    { label: "Seen & loved", emoji: "👀❤️" },
    { label: "Forever feeling", emoji: "♾️❤️" },
    { label: "Home in you", emoji: "🏠💖" },   
 ],
  },
  {
    key: "Mental",
    title: "Mental state",
    moods: [
      { label: "Anxious", emoji: "😰" },
      { label: "Confused", emoji: "😕" },
      { label: "Overthinking", emoji: "🤯" },
       { label: "Clear-minded", emoji: "🧠✨" },
    { label: "Mentally calm", emoji: "🌿" },
    { label: "Overthinking", emoji: "🔁" },
    { label: "Mentally tired", emoji: "💤🧠" },
    { label: "Focused", emoji: "🎯" },
    { label: "Distracted", emoji: "🌫️" },
    { label: "Mentally strong", emoji: "💪🧠" },
    { label: "Mentally drained", emoji: "🔋⬇️" },
    { label: "Sharp thinking", emoji: "⚡🧠" },
    { label: "Foggy mind", emoji: "🌁" },
    { label: "Balanced mind", emoji: "⚖️" },
    { label: "Racing thoughts", emoji: "🏃‍♂️💭" },
    { label: "Grounded", emoji: "🪨" },
    { label: "Mentally peaceful", emoji: "🕊️🧠" },
    { label: "Overloaded", emoji: "📚🧠" },
    { label: "Stable", emoji: "🧩" },
    { label: "Mentally alert", emoji: "👀🧠" },
    { label: "Confused", emoji: "🤯" },
    { label: "In control", emoji: "🎛️" },
    { label: "Mentally overwhelmed", emoji: "🌊🧠" },
    { label: "Calm but thinking", emoji: "🌙💭" },
    { label: "Thoughtful", emoji: "🤔" },
    { label: "Mind at ease", emoji: "😌🧠" },
    { label: "Mentally restless", emoji: "🔄" },
    { label: "Clear but quiet", emoji: "🌫️✨" },
    { label: "Deep in thought", emoji: "🌊💭" },
    { label: "Mindful", emoji: "🧘‍♂️" },
    { label: "Scattered thoughts", emoji: "🧠💥" },
    { label: "Mentally open", emoji: "🚪🧠" },
    { label: "Inner clarity", emoji: "🔮" },
    ],
  },
  {
    key: "Stress",
    title: "Stress",
    moods: [
      { label: "Stressed", emoji: "😣" },
      { label: "Overwhelmed", emoji: "😵" },
      { label: "Burned out", emoji: "🔥" },
      { label: "Stressed", emoji: "😣" },
    { label: "Under pressure", emoji: "🧱" },
    { label: "Burned out", emoji: "🔥⬇️" },
    { label: "Overwhelmed", emoji: "😵‍💫" },
    { label: "Tense", emoji: "😬" },
    { label: "Mentally pressured", emoji: "🧠🧱" },
    { label: "Emotionally strained", emoji: "💢" },
    { label: "Stressed but coping", emoji: "🫱" },
    { label: "Deadline pressure", emoji: "⏰" },
    { label: "Work stressed", emoji: "💼😓" },
    { label: "Life pressure", emoji: "🌍" },
    { label: "Internally stressed", emoji: "🌪️🧠" },
    { label: "Overloaded mind", emoji: "📚😵" },
    { label: "Stress building up", emoji: "📈" },
    { label: "Barely holding it together", emoji: "🫠" },
    { label: "Heavy inside", emoji: "🪨💔" },
    { label: "Pushed too far", emoji: "🚧" },
    { label: "Stress fatigue", emoji: "💤😣" },
    { label: "Pressure everywhere", emoji: "🌍🧱" },
    { label: "Stressed and tired", emoji: "😩" },
    { label: "Emotionally pressured", emoji: "💭🧱" },
    { label: "Stress spiral", emoji: "🌀" },
    { label: "Feeling boxed in", emoji: "📦" },
    { label: "No breathing space", emoji: "😮‍💨" },
    { label: "Stress headache", emoji: "🤕" },
    { label: "Constant pressure", emoji: "🔁" },
    { label: "On edge", emoji: "⚡" },
    { label: "Stress overload", emoji: "🚨" },
    { label: "Need a break", emoji: "🛑" },
    { label: "Stress taking over", emoji: "🌊" },
    ],
  },
  {
    key: "Creative",
    title: "Creative",
    moods: [
      { label: "Inspired", emoji: "✨" },
      { label: "Creative", emoji: "🎨" },
      { label: "Imaginative", emoji: "🧠" },
      { label: "Creative flow", emoji: "✨" },
    { label: "Inspired", emoji: "🎨" },
    { label: "Full of ideas", emoji: "💡" },
    { label: "Artist mode", emoji: "🖌️" },
    { label: "Writing mood", emoji: "✍️" },
    { label: "Creative spark", emoji: "⚡" },
    { label: "Imaginative", emoji: "🌈" },
    { label: "Storytelling energy", emoji: "📖" },
    { label: "Visionary", emoji: "👁️" },
    { label: "Creating quietly", emoji: "🌿" },
    { label: "Designing something", emoji: "🧩" },
    { label: "Deep creative focus", emoji: "🎯" },
    { label: "Expressive", emoji: "💬" },
    { label: "Musical mood", emoji: "🎵" },
    { label: "Drawing thoughts", emoji: "✏️" },
    { label: "Creative curiosity", emoji: "🧠" },
    { label: "Idea brewing", emoji: "☕" },
    { label: "Exploring ideas", emoji: "🧭" },
    { label: "Creative confidence", emoji: "😌" },
    { label: "Free expression", emoji: "🕊️" },
    { label: "Visual thinking", emoji: "🖼️" },
    { label: "Building something new", emoji: "🏗️" },
    { label: "Flowing ideas", emoji: "🌊" },
    { label: "Creative reflection", emoji: "🔍" },
    { label: "Inspired but calm", emoji: "🌱" },
    { label: "Art healing", emoji: "🎭" },
    { label: "Creative release", emoji: "💫" },
    { label: "Thinking in colors", emoji: "🌈🖌️" },
    { label: "Making sense creatively", emoji: "🧠✨" },
    { label: "Creative peace", emoji: "🧘‍♂️🎨" },
    ],
  },
  {
    key: "Confidence",
    title: "Confidence",
    moods: [
      { label: "Confident", emoji: "😎" },
      { label: "Proud", emoji: "🏆" },
      { label: "Bold", emoji: "🦁" },
      { label: "Confident", emoji: "😎" },
    { label: "Self-assured", emoji: "🧍‍♂️✨" },
    { label: "Bold energy", emoji: "🔥" },
    { label: "Standing tall", emoji: "🧱" },
    { label: "Inner strength", emoji: "💠" },
    { label: "Calm confidence", emoji: "🌿" },
    { label: "Believing in myself", emoji: "💛" },
    { label: "Unshakable", emoji: "🪨" },
    { label: "Focused and confident", emoji: "🎯" },
    { label: "Secure in myself", emoji: "🔐" },
    { label: "Owning my voice", emoji: "🎙️" },
    { label: "Grounded confidence", emoji: "🌍" },
    { label: "Quietly powerful", emoji: "🤍" },
    { label: "Feeling capable", emoji: "🛠️" },
    { label: "Sure of my path", emoji: "🧭" },
    { label: "Confident growth", emoji: "🌱" },
    { label: "Trusting myself", emoji: "🧠💛" },
    { label: "Comfortable in my skin", emoji: "🫶" },
    { label: "Steady confidence", emoji: "⚖️" },
    { label: "Clear-headed confidence", emoji: "🧠✨" },
    { label: "Self-respect", emoji: "🪞" },
    { label: "Confident presence", emoji: "👁️" },
    { label: "Inner calm, outer strength", emoji: "🌊💪" },
    { label: "Resilient confidence", emoji: "🔁" },
    { label: "Confident clarity", emoji: "💎" },
    { label: "Feeling empowered", emoji: "⚡" },
    { label: "Self-belief activated", emoji: "🔓" },
    { label: "Confident but humble", emoji: "🙏" },
    { label: "Ready for anything", emoji: "🚀" },
    { label: "Confidence rising", emoji: "📈" },
    ],
  },
  {
    key: "Pain",
    title: "Pain",
    moods: [
      { label: "Heartbroken", emoji: "💔" },
      { label: "Hurt", emoji: "😞" },
      { label: "Grieving", emoji: "🖤" },
      { label: "In pain", emoji: "🩹" },
    { label: "Hurting inside", emoji: "💔" },
    { label: "Emotional pain", emoji: "😞" },
    { label: "Quiet pain", emoji: "🤍" },
    { label: "Heavy heart", emoji: "🪨❤️" },
    { label: "Deeply hurt", emoji: "🥀" },
    { label: "Painful memories", emoji: "🧠💭" },
    { label: "Carrying pain", emoji: "🎒" },
    { label: "Unspoken pain", emoji: "🤐" },
    { label: "Still hurting", emoji: "🌧️" },
    { label: "Pain but holding on", emoji: "🫶" },
    { label: "Tender inside", emoji: "🌱" },
    { label: "Pain resurfacing", emoji: "🌊" },
    { label: "Wounded feelings", emoji: "🩸" },
    { label: "Pain that lingers", emoji: "⏳" },
    { label: "Fragile today", emoji: "🧩" },
    { label: "Emotionally sore", emoji: "🤕" },
    { label: "Soft but hurting", emoji: "🫧" },
    { label: "Pain beneath the smile", emoji: "🙂💔" },
    { label: "Trying despite pain", emoji: "🚶‍♂️" },
    { label: "Ache in my heart", emoji: "💗" },
    { label: "Bruised emotions", emoji: "🟣" },
    { label: "Quiet suffering", emoji: "🌫️" },
    { label: "Painful growth", emoji: "🌱💔" },
    { label: "Healing through pain", emoji: "🩹✨" },
    { label: "Pain I can’t explain", emoji: "🫥" },
    { label: "Carrying scars", emoji: "🧵" },
    { label: "Still healing", emoji: "🕊️" },
    { label: "Pain seeking release", emoji: "🌬️" },
    { label: "Surviving the pain", emoji: "🌤️" },
    ],
  },
];
